"""refactor elo tables to per-player schema

Revision ID: b1f888ad99af
Revises: 1e10278a02b4
Create Date: 2026-07-29 20:27:27.611449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1f888ad99af'
down_revision: Union[str, Sequence[str], None] = '1e10278a02b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_match_record',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), nullable=False, comment='赛事ID，逻辑外键 → motion_event.event_id（数据链路保证，不设数据库 FK）'),
    sa.Column('battle_id', mysql.INTEGER(), nullable=False, comment='对阵ID，逻辑外键 → motion_event_layout_stage_battle.battle_id（同上）'),
    sa.Column('source_order', mysql.INTEGER(), nullable=False, comment='赛事内场序号（event_index），用于回放排序'),
    sa.Column('user_id', mysql.BIGINT(), nullable=True, comment='选手用户ID'),
    sa.Column('team_side', mysql.VARCHAR(length=1), nullable=False, comment='所在方 A 或 B'),
    sa.Column('team_size', mysql.TINYINT(), nullable=False, comment='队内人数 1=单打 2=双打'),
    sa.Column('is_winner', mysql.TINYINT(), nullable=False, comment='本方是否获胜 1=是 0=否'),
    sa.Column('rating_before', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='赛前 Elo'),
    sa.Column('delta', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='Elo 变化（正=加分，负=减分）'),
    sa.Column('rating_after', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='赛后 Elo'),
    sa.Column('expected', mysql.DECIMAL(precision=10, scale=4), nullable=False, comment='本方预期胜率 E'),
    sa.Column('k_factor', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='K 值'),
    sa.Column('weight_multiplier', mysql.DECIMAL(precision=10, scale=4), nullable=False, comment='赛事权重 M_weight'),
    sa.Column('margin_multiplier', mysql.DECIMAL(precision=10, scale=4), nullable=False, comment='分差倍率 M_margin'),
    sa.Column('base_delta', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='clamp 前的普通变化'),
    sa.Column('clamped_delta', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='clamp 后的普通变化'),
    sa.Column('upset_bonus', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='越级加分 bonus'),
    sa.Column('upset_penalty', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='被越级扣分 penalty'),
    sa.Column('opponent_user_id', mysql.BIGINT(), nullable=True, comment='对手用户ID（双打时为第一个对手）'),
    sa.Column('opponent_partner_id', mysql.BIGINT(), nullable=True, comment='双打时第二个对手，单打为 NULL'),
    sa.Column('score_self', mysql.INTEGER(), nullable=False, comment='本方得分'),
    sa.Column('score_opponent', mysql.INTEGER(), nullable=False, comment='对方得分'),
    sa.Column('played_at', mysql.DATETIME(), nullable=True, comment='比赛时间（来自 battle_time，可为空）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elo_player_rating',
    sa.Column('user_id', mysql.BIGINT(), nullable=False, comment='用户ID，逻辑外键 → motion_user.user_id（数据链路保证，不设数据库 FK）'),
    sa.Column('sport_type', mysql.VARCHAR(length=32), nullable=False, comment='运动品类，如 badminton / tabletennis'),
    sa.Column('rating', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='当前 Elo 分'),
    sa.Column('games', sa.Integer(), nullable=False, comment='总比赛场次'),
    sa.Column('wins', sa.Integer(), nullable=False, comment='胜场'),
    sa.Column('losses', sa.Integer(), nullable=False, comment='负场'),
    sa.Column('draws', sa.Integer(), nullable=False, comment='平场'),
    sa.Column('highest_rating', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='历史最高 Elo 分'),
    sa.Column('lowest_rating', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='历史最低 Elo 分'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_id', 'sport_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elo_player_rating')
    op.drop_table('elo_match_record')
    # ### end Alembic commands ###
